{{- if .Values.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "csi-driver.storageClass.name" .}}
{{- if .Values.storageClass.default }}
  annotations:
    "storageclass.kubernetes.io/is-default-class": "true"
{{- end }}
provisioner: {{ include "csi-driver.driver.name" . }}
{{- with .Values.storageClass.parameters }}
parameters:
{{- toYaml . | nindent 2}}
{{- end }}
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
{{- end }}
