name: pull-request

on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
          USERNAME: ${{ secrets.CI_USERNAME }}
        run: git config --global url."https://${USERNAME}:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0

      - name: Test
        run: make test

      - name: Build
        run: make

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.15
        with:
          token: ${{secrets.CODECOV_UPLOAD_TOKEN}}
          file: ./coverage.txt

      # - name: Notify slack success
      #   if: success()
      #   uses: rtCamp/action-slack-notify@master
      #   env:
      #     SLACK_COLOR: good
      #     SLACK_MESSAGE: ${{ github.event.pull_request._links.html.href }}
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      # - name: Notify slack fail
      #   if: failure()
      #   uses: rtCamp/action-slack-notify@master
      #   env:
      #     SLACK_COLOR: danger
      #     SLACK_MESSAGE: ${{ github.event.pull_request._links.html.href }}
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
