name: compatibility-verify

on:
  pull_request:
    branches: [master]

jobs:
  k8s1-22-compatibility-verify:
    uses: smartxworks/elf-csi-driver/.github/workflows/compatibility-verify-template.yaml@master
    with:
      kubeVersion: "k8s-1.22"
    secrets:
      zbs-cluster-vip: ${{ secrets.E2E_ZBS_CLUSTER_VIP }}